// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: nativeBridge.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.pj.core.proto;

