// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: NativePubSub.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.pj.pubsub.proto;

@kotlin.jvm.JvmName("-initializeenvelope")
public inline fun envelope(block: com.pj.pubsub.proto.EnvelopeKt.Dsl.() -> kotlin.Unit): com.pj.pubsub.proto.NativePubSub.Envelope =
  com.pj.pubsub.proto.EnvelopeKt.Dsl._create(com.pj.pubsub.proto.NativePubSub.Envelope.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `Envelope`
 */
public object EnvelopeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.pj.pubsub.proto.NativePubSub.Envelope.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.pj.pubsub.proto.NativePubSub.Envelope.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.pj.pubsub.proto.NativePubSub.Envelope = _builder.build()

    /**
     * `.Message message = 1;`
     */
    public var message: com.pj.pubsub.proto.NativePubSub.Message
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * `.Message message = 1;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
    /**
     * `.Message message = 1;`
     * @return Whether the message field is set.
     */
    public fun hasMessage(): kotlin.Boolean {
      return _builder.hasMessage()
    }

    /**
     * `int32 senderID = 2;`
     */
    public var senderID: kotlin.Int
      @JvmName("getSenderID")
      get() = _builder.getSenderID()
      @JvmName("setSenderID")
      set(value) {
        _builder.setSenderID(value)
      }
    /**
     * `int32 senderID = 2;`
     */
    public fun clearSenderID() {
      _builder.clearSenderID()
    }

    /**
     * `optional int32 receiverID = 3;`
     */
    public var receiverID: kotlin.Int
      @JvmName("getReceiverID")
      get() = _builder.getReceiverID()
      @JvmName("setReceiverID")
      set(value) {
        _builder.setReceiverID(value)
      }
    /**
     * `optional int32 receiverID = 3;`
     */
    public fun clearReceiverID() {
      _builder.clearReceiverID()
    }
    /**
     * `optional int32 receiverID = 3;`
     * @return Whether the receiverID field is set.
     */
    public fun hasReceiverID(): kotlin.Boolean {
      return _builder.hasReceiverID()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class TagNamesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string tagNames = 4;`
     * @return A list containing the tagNames.
     */
    public val tagNames: com.google.protobuf.kotlin.DslList<kotlin.String, TagNamesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getTagNamesList()
      )
    /**
     * `repeated string tagNames = 4;`
     * @param value The tagNames to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addTagNames")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagNamesProxy>.add(value: kotlin.String) {
      _builder.addTagNames(value)
    }
    /**
     * `repeated string tagNames = 4;`
     * @param value The tagNames to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignTagNames")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagNamesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string tagNames = 4;`
     * @param values The tagNames to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllTagNames")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagNamesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllTagNames(values)
    }
    /**
     * `repeated string tagNames = 4;`
     * @param values The tagNames to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllTagNames")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagNamesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string tagNames = 4;`
     * @param index The index to set the value at.
     * @param value The tagNames to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setTagNames")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagNamesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setTagNames(index, value)
    }/**
     * `repeated string tagNames = 4;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearTagNames")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagNamesProxy>.clear() {
      _builder.clearTagNames()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun com.pj.pubsub.proto.NativePubSub.Envelope.copy(block: `com.pj.pubsub.proto`.EnvelopeKt.Dsl.() -> kotlin.Unit): com.pj.pubsub.proto.NativePubSub.Envelope =
  `com.pj.pubsub.proto`.EnvelopeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.pj.pubsub.proto.NativePubSub.EnvelopeOrBuilder.messageOrNull: com.pj.pubsub.proto.NativePubSub.Message?
  get() = if (hasMessage()) getMessage() else null

